SUPABASE_URL = "https://ctgbcvfbupgumkudufqm.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0Z2JjdmZidXBndW1rdWR1ZnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5NzkwOTYsImV4cCI6MjA4MTU1NTA5Nn0.L6WlkcQva89Lel2XgCiBs1HvzdnsgLOI8aTOHUG_FqU"
GEMINI_API_KEY = "AQ.Ab8RN6JxPI7Tk2PnRmi3Y2DtTzQiaG-cAsqVJZkjIbou-YpCSw"
GEMINI_MODEL = "gemini-3.5-flash"
